# Simplified LiveKit setup for demo without ingress
services:
  livekit:
    image: livekit/livekit-server:latest
    command: --dev
    ports:
      - '7880:7880'
      - '7881:7881'
      - '7882:7882/udp'
    environment:
      LIVEKIT_KEYS: "devkey: secret"
