services:
  livekit:
    image: livekit/livekit-server:latest
    command: >
      --dev
      --api-keys devkey:secret
      --bind 0.0.0.0
      --port 7880
      --rtc.udp_port 7882
      --rtc.tcp_port 7881
    ports:
      - '7880:7880'   # LiveKit HTTP API / WebSocket
      - '7881:7881'   # LiveKit TCP TURN
      - '7882:7882/udp' # LiveKit UDP media
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:7880/"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  ingress:
    image: livekit/ingress:latest
    environment:
      INGRESS_CONFIG_FILE: /etc/ingress.yaml
    volumes:
      - ./config/ingress.yaml:/etc/ingress.yaml
    depends_on:
      livekit:
        condition: service_healthy
    ports:
      - '8080:8080'   # WHIP HTTP endpoint
      - '8089:8089'   # Health check endpoint


